version: '3'

services:
  app:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build: ./docker
    image: blog-dev
    volumes:
      - ${PWD}/www:/var/www
    ports:
      - ${CONTAINER_PORT}:80
    networks:
      - sitemodelemvc
    env_file:
      - .env

  mysql:
    container_name:  ${CONTAINER_MYSQL}
    restart: unless-stopped
    image: mariadb
    expose:
      - "${SQL_INTERNAL_PORT}"
    ports:
      - ${SQL_CLIENT_PORT}:${SQL_INTERNAL_PORT} 
    networks: 
      - sitemodelemvc
    env_file:
      - .env
  mail:
    container_name:  ${CONTAINER_NAME}.mailcatcher
    restart: unless-stopped
    image: schickling/mailcatcher
    ports:
      - ${PORT_MAIL}:1080
    networks: 
      - sitemodelemvc
    env_file:
      - .env

networks: 
  sitemodelemvc:
    driver: bridge
